server:
  port: 8080



spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false

  datasource:

    url: jdbc:mysql://localhost:3306/cadpedidos
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000